from typing import Protocol
from abc import abstractmethod


class Plotter(Protocol):
    @abstractmethod
    def disconnect(self): ...
    @abstractmethod
    def goto(self, x_target, y_target): ...
    @abstractmethod
    def go(self, x_delta, y_delta): ...
    @abstractmethod
    def lineto(self, x_target, y_target): ...
    @abstractmethod
    def line(self, x_delta, y_delta): ...
    @abstractmethod
    def moveto(self, x_target, y_target): ...
    @abstractmethod
    def move(self, x_delta, y_delta): ...
    @abstractmethod
    def draw_path(self, vertex_list): ...
    @abstractmethod
    def turtle_pos(self): ...
    @abstractmethod
    def current_pos(self) -> dict: ...
    @abstractmethod
    def update(self): ...
    @abstractmethod
    def usb_query(self, query): ...
    @abstractmethod
    def usb_command(self, command): ...
    @abstractmethod
    def penup(self): ...
    @abstractmethod
    def pendown(self): ...
    @abstractmethod
    def block(self): ...
    @abstractmethod
    def delay(self, time_ms): ...
    @abstractmethod
    def current_pen(self) -> bool: ...
    @abstractmethod
    def turtle_pen(self) -> bool: ...
    @abstractmethod
    def interactive(self): ...
    @abstractmethod
    def connect(self) -> bool: ...
    @abstractmethod
    def load_config(self, config_ref): ...
